<?php
/**
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author    Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license   LGPL-3.0
 * @license   http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link      https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013-2014 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
?>
<table class="table table-hover">
    <thead>
    <tr>
        <td>#</td>
        <td><?php echo $this->translate('Username'); ?></td>
        <td><?php echo $this->translate('Roles'); ?></td>
        <td><?php echo $this->translate('Last login'); ?></td>
        <td><?php echo $this->translate('Logins'); ?></td>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->users as $user): ?>
        <tr>
            <td>
                <a href="<?php echo $this->url('user/profile', array('id' => $user->getId())); ?>"><?php echo $user->getUsername(); ?></a>
            </td>
            <td><?php echo $user->getEmail(); ?></td>
            <td><?php echo implode(', ', $user->getRoles()->toArray()); ?></td>
            <td><span class="timeago"
                      title="<?php echo $user->getLastLogin() ? $this->timeago()->format($user->getLastLogin()) : ''; ?>"></span>
            </td>
            <td><?php echo $user->getLogins(); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>