<?php
/**
 * This file is part of Athene2.
 *
 * Copyright (c) 2013-2019 Serlo Education e.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 * you may not use this file except in compliance with the License
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @copyright Copyright (c) 2013-2019 Serlo Education e.V.
 * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache License 2.0
 * @link      https://github.com/serlo-org/athene2 for the canonical source repository
 */
?>
<table class="table table-hover">
    <thead>
    <tr>
        <td>#</td>
        <td><?php echo $this->translate('Username'); ?></td>
        <td><?php echo $this->translate('Roles'); ?></td>
        <td><?php echo $this->translate('Last login'); ?></td>
        <td><?php echo $this->translate('Logins'); ?></td>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->users as $user): ?>
        <tr>
            <td>
                <a href="<?php echo $this->url('user/profile', array('id' => $user->getId())); ?>"><?php echo $user->getUsername(); ?></a>
            </td>
            <td><?php echo $user->getEmail(); ?></td>
            <td><?php echo implode(', ', $user->getRoles()->toArray()); ?></td>
            <td><span class="timeago"
                      title="<?php echo $user->getLastLogin() ? $this->timeago()->format($user->getLastLogin()) : ''; ?>"></span>
            </td>
            <td><?php echo $user->getLogins(); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>