<?php echo $this->pageHeader('A fatal error occurred'); ?>

    <p><?php echo $this->translate('While we\'re resolving this issue, please enjoy the video.'); ?></p>

<iframe width="700" height="394" src="//www.youtube-nocookie.com/embed/Ktbhw0v186Q?rel=0" frameborder="0" allowfullscreen></iframe>

<hr/>

<?php ob_start(); ?>

<?php if(isset($this->exception) && $this->exception instanceof Exception): ?>
<div class="well">
<h2><?php echo $this->translate('Additional information') ?>:</h2>
<h3><?php echo get_class($this->exception); ?></h3>
<dl>
    <dt><?php echo $this->translate('File') ?>:</dt>
    <dd>
        <pre class="prettyprint linenums"><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine() ?></pre>
    </dd>
    <dt><?php echo $this->translate('Message') ?>:</dt>
    <dd>
        <pre class="prettyprint linenums"><?php echo $this->exception->getMessage() ?></pre>
    </dd>
    <dt><?php echo $this->translate('Stack trace') ?>:</dt>
    <dd>
        <pre class="prettyprint linenums"><?php echo $this->exception->getTraceAsString() ?></pre>
    </dd>
</dl>
<?php
    $e = $this->exception->getPrevious();
    if ($e) :
?>
<hr/>
<h2><?php echo $this->translate('Previous exceptions') ?>:</h2>
<ul class="unstyled">
    <?php while($e) : ?>
    <li>
        <h3><?php echo get_class($e); ?></h3>
        <dl>
            <dt><?php echo $this->translate('File') ?>:</dt>
            <dd>
                <pre class="prettyprint linenums"><?php echo $e->getFile() ?>:<?php echo $e->getLine() ?></pre>
            </dd>
            <dt><?php echo $this->translate('Message') ?>:</dt>
            <dd>
                <pre class="prettyprint linenums"><?php echo $e->getMessage() ?></pre>
            </dd>
            <dt><?php echo $this->translate('Stack trace') ?>:</dt>
            <dd>
                <pre class="prettyprint linenums"><?php echo $e->getTraceAsString() ?></pre>
            </dd>
        </dl>
    </li>
    <?php
        $e = $e->getPrevious();
        endwhile;
    ?>
</ul>
<?php endif; ?>

<?php else: ?>

<h3><?php echo $this->translate('No Exception available') ?></h3>

</div>

<?php endif ?>

<?php

$output = ob_get_contents();

ob_end_clean();

if (isset($this->display_exceptions) && $this->display_exceptions){
    echo $output;
} else {
    echo '<p>'.$this->translate('Read the following, if you\'re really good with computers:').'</p>';
    echo '<textarea rows="50" class="form-control">';
    echo $this->encrypt($output);
    echo '</textarea>';
}