<?php
/**
 * This file is part of Athene2.
 *
 * Copyright (c) 2013-2019 Serlo Education e.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 * you may not use this file except in compliance with the License
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @copyright Copyright (c) 2013-2019 Serlo Education e.V.
 * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache License 2.0
 * @link      https://github.com/serlo-org/athene2 for the canonical source repository
 */
/**
* @authors Kanstantsin A Kamkou (2ka.by); Jeroen Herczeg
* 
* renders first level menu items as 1of6 columns
*/
$html = array(
    '<ul class="nav nav-pills">',
);

foreach ($this->container as $page) {

    if (! $page->isVisible() || !$this->navigation()->accept($page)) {
        continue;
    }

    // header
    // $html[] = '<li class="nav-header">';
    $html[] = '<li>';
    $html[] = '<a href="' . $this->alias($page->getHref()) . '">';
    if ($page->get('icon')) {
        $html[] = '<i class="icon-' . $page->get('icon') . '"></i>';
    }
    $html[] = $page->getLabel();
    $html[] = "</a>";
    $html[] = "</li>";
    
    if (! empty($page->pages)) {

        foreach ($page->pages as $subpage) {
            // visibility of the sub-page
            if (! $subpage->isVisible()) {
                continue;
            }
            if ($subpage->getLabel() == 'divider') {
                $html[] = '<li class="divider"></li>';
                continue;
            }
            $html[] = '<li' . ($subpage->isActive() ? ' class="active"' : '') . '>';
            $html[] = '<a href="' . $this->alias($page->getHref()) . '">';
            
            if ($subpage->get('icon')) {
                $html[] = '<i class="icon-' . $subpage->get('icon') . '"></i>';
            }
            
            $html[] = $subpage->getLabel();
            $html[] = "</a>";
            $html[] = "</li>";
        }
    }

}

$html[] = '</ul>';

echo join(' ', $html);