<?php
/**
 * This file is part of Athene2.
 *
 * Copyright (c) 2013-2018 Serlo Education e.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 * you may not use this file except in compliance with the License
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @copyright Copyright (c) 2013-2018 Serlo Education e.V.
 * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache License 2.0
 * @link      https://github.com/serlo-org/athene2 for the canonical source repository
 */
$html = array();
//$html[] = '<div class="navbar navbar-fixed-top">';
//$html[] = ' <div class="navbar-inner">';
//$html[] = ' <div class="container">';

$html[] = '<nav>';
$html[] = '<div id="navigation-content">';
$html[] = '<ul id="main-nav" class="nav" itemscope itemtype="http://data-vocabulary.org/Breadcrumb">';

foreach ($this->container as $page) {
    // visibility of the page
    if (!$page->isVisible(false) || !$this->navigation()->accept($page) || !$page->isActive(true)) {
        continue;
    }

    // for Login/Logout/Register links:
    // check if menu item has 'needsIdentity' set
    if (!is_null($page->get('needsIdentity'))) {
        // convert value of key 'needsIdentity' to boolean if necessary
        $needsIdentity = is_bool($page->get('needsIdentity')) ? $page->get('needsIdentity') : ($page->get('needsIdentity') === 'true');
        // check if current user is anonymous and compare to 'needsIdentity' value
        if ($this->isGranted('login') !== $needsIdentity) {
            continue;
        }
    }

    $translate = is_bool($page->get('translate')) ? $page->get('translate') : $page->get('translate') === 'true';
    $label = $translate ? $this->translate($page->getLabel()) : $page->getLabel();

    $html[] = '<li class="is-hidden">';
    $html[] = '<a class="is-hidden" href="' . $page->getHref() . '" itemprop="url">';
    $html[] = '<span itemprop="title">' . $label . '</span>';
    $html[] = '</a>';
    $html[] = '</li>';

    if (!empty($page->pages)) {
        // $html[] = '<ul class="dropdown-menu">';
        $html[] = $this->partial('layout/navigation/partial/nested-navigation-list-asynchable', array('pages' => $page->pages));
        // $html[] = "</ul>";
    }
}

$html[] = '</ul>';
$html[] = '</div>';
$html[] = '</nav>';

echo join(' ', $html);
