<?php
/**
 * This file is part of Athene2.
 *
 * Copyright (c) 2013-2019 Serlo Education e.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 * you may not use this file except in compliance with the License
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @copyright Copyright (c) 2013-2019 Serlo Education e.V.
 * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache License 2.0
 * @link      https://github.com/serlo-org/athene2 for the canonical source repository
 */
$html = array();
$html[] = '<ul id="side-navigation-social">';


foreach ($this->container as $page) {
    // visibility of the page
    if (!$page->isVisible(false) || !$this->navigation()->accept($page)) {
        echo 'skip it!';
        continue;
    }

    // for Login/Logout/Register links:
    // check if menu item has 'needsIdentity' set
    if (!is_null($page->get('needsIdentity'))) {
        // convert value of key 'needsIdentity' to boolean if necessary
        $needsIdentity = is_bool($page->get('needsIdentity')) ? $page->get('needsIdentity') : ($page->get('needsIdentity') === 'true');
        // check if current user is anonymous and compare to 'needsIdentity' value
        if ($this->isGranted('login') !== $needsIdentity) {
            continue;
        }
    }

    $html[] = '<li' . (($page->get('icon') && !$page->get('label')) ? ' class="icon-only"' : '') . '>';
    $html[] = '<a href="' . $this->alias($page->getHref()) . '" class="' . $page->get('class') . '">';

    if ($page->get('icon')) {
        if (stristr($page->get('icon'), 'fa-')) {
            $html[] = '<span class="' . $page->get('icon') . '"></span>';
        } else {
            $html[] = '<span class="fa fa-' . $page->get('icon') . '"></span>';
        }
        $html[] = '<span class="sr-only">' . $page->getLabel() . '</span>';
    } else {
        $html[] = $page->getLabel();
    }

    $html[] = '</a>';
}

$html[] = '</ul>';
echo join(' ', $html);
