<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author  Julian Kempff (julian.kempff@serlo.org)
 * @license LGPL-3.0
 * @license http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link        https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */

$html = array();

foreach ($this->container as $page) {
    $html[] = '<div class="row">';
    $html[] = '<div class="col-xs-5">';
    $html[] = '<div class="nav-label">' . $page->getLabel() . '</div>';
    $html[] = '</div>';
    $html[] = '<div class="col-xs-7">';

    //if(! empty($page->pages)) {
    //    $html[] = '<ul class="nav">';
    //    $html[] = $this->partial('layout/navigation/partial/nested-navigation-list', array('pages' => $page->pages, 'useBreadCrumbs' => false));
    //    $html[] = "</ul>";
    //}

    $html[] = '</div>';
    $html[] = '</div>';
}

echo join(' ', $html);