<?php
/**
 * This file is part of Athene2.
 *
 * Copyright (c) 2013-2019 Serlo Education e.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 * you may not use this file except in compliance with the License
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @copyright Copyright (c) 2013-2019 Serlo Education e.V.
 * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache License 2.0
 * @link      https://github.com/serlo-org/athene2 for the canonical source repository
 */
/**
* @authors Kanstantsin A Kamkou (2ka.by); Jeroen Herczeg
*/
$html = array(
    '<ul class="nav nav-list">'
);

foreach ($this->container as $page) {
    // show only the current branch and the visible item
    if (! $page->isVisible() || !$this->navigation()->accept($page)) {
        continue;
    }
    
    // header
    $html[] = '<li>';

    if ($page->get('icon')) {
        if (stristr($page->get('icon'), 'fa-')) {
            $html[] = '<span class="' . $page->get('icon') . '"></span>';
        } else {
            $html[] = '<span class="fa fa-' . $page->get('icon') . '"></span>';
        }
    }

    $html[] = '<a href="' . $this->alias($page->getHref()) . '">';
    $html[] = $page->getLabel();
    $html[] = '</a>';
    
    if (! empty($page->pages)) {
        $html[] = '<ul>';
        $html[] = $this->partial('layout/navigation/partial/nested-dropdown-navigation-list', array('pages' => $page->pages));
        $html[] = "</ul>";
    }

    $html[] = "</li>";
}

$html[] = '</ul>';

echo join(' ', $html);