<?php
/**
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author      Jakob Pfab (jakob.pfab@serlo.org)
 * @license     MIT License
 * @license     http://opensource.org/licenses/MIT The MIT License (MIT)
 * @link        https://github.com/serlo-org/athene2 for the canonical source repository
 */
namespace Cache\Strategy;

use StrokerCache\Strategy\Route;
use Zend\Mvc\MvcEvent;
use User\Manager\UserManager;

class RouteStrategy extends Route
{
    public function shouldCache(MvcEvent $event)
    {

        $app            = $event->getApplication();
        $serviceManager = $app->getServiceManager();
        /* @var $userManager UserManager */
        $userManager = $serviceManager->get('User\Manager\UserManager');
        if ($userManager->getUserFromAuthenticator()) {
            return false;
        }
        return parent::shouldCache($event); // TODO: Change the autogenerated stub
    }
}
