<?php
/**
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author      Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license   http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
 * @link        https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright   Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
echo $this->doctype();
?>
<html class="fuelux" lang="<?php echo $this->currentLanguage(); ?>">
<?php echo $this->partial('layout/partials/head'); ?>
<body itemscope itemtype="http://schema.org/WebPage">
<div class="wrap">
    <?php echo $this->partial('layout/partials/header'); ?>

    <div id="page" class="container clearfix">
        <section class="main clearfix">
            <div id="content-layout" class="content clearfix">
                <?php echo $this->partial('layout/partials/notifications'); ?>
                <?php echo $this->partial('layout/partials/main'); ?>
            </div>
            <?php echo $this->banner(); ?>
            <?php echo $this->placeholder('discussions'); ?>
            <?php echo $this->horizon(3); ?>
        </section>
    </div>
    <div id="footer-push"></div>
</div>
<?php echo $this->partial('layout/partials/footer'); ?>
<?php echo $this->partial('layout/partials/default-modal'); ?>
<?php echo $this->placeholder('modals'); ?>
<?php echo $this->tracking(); ?>
<?php echo $this->partial('layout/partials/noscript'); ?>
</body>
</html>
