<?php
/**
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author      Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license   http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
 * @link        https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright   Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
echo $this->doctype();

$classes = array('wrap');

if ($this->layout()->fullWidth) {
    array_push($classes, 'full-width');
}

if (!$this->layout()->hideLeftSidebar) {
    array_push($classes, 'has-navigation');
}

if (!$this->layout()->hideRightSidebar) {
    array_push($classes, 'has-context');
}

$class = join(' ', $classes);

$pageClasses = array('clearfix');

if (!empty($this->registry()->get('rnav'))) {
    array_push($pageClasses, 'has-sidebar');
}

if (!$this->layout()->fullWidth) {
    array_push($pageClasses, 'container');
}

$pageClass = join(' ', $pageClasses);
?>
<!--[if lt IE 9 ]>
<html class="old-ie fuelux" lang="<?php echo $this->currentLanguage(); ?>"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html class="fuelux" lang="<?php echo $this->currentLanguage(); ?>"> <!--<![endif]-->
<head>
    <?php echo $this->partial('layout/partials/head'); ?>
    <?php echo $this->partial('layout/partials/styles'); ?>
</head>
<body itemscope itemtype="http://schema.org/WebPage">
<div class="<?php echo $class ?>">
    <?php echo $this->partial('layout/partials/header'); ?>

    <div id="page" class="<?php echo $pageClass ?>">
        <?php echo $this->partial('layout/partials/left-sidebar'); ?>
        <section class="main clearfix">
            <div id="content-layout" class="content clearfix">
                <?php echo $this->partial('layout/partials/notifications'); ?>
                <?php echo $this->partial('layout/partials/main'); ?>
            </div>
            <?php echo $this->partial('layout/partials/banner'); ?>
            <?php echo $this->partial('layout/partials/discussions'); ?>
            <?php $isCourse = $this->registry()->get('rnav-is-course'); ?>
            <?php if (empty($isCourse) || !$isCourse): ?>
                <?php echo $this->partial('layout/partials/right-sidebar'); ?>
            <?php endif; ?>
            <?php echo $this->partial('layout/partials/horizon'); ?>
        </section>
    </div>
    <div id="footer-push"></div>
</div>
<?php echo $this->partial('layout/partials/footer'); ?>
<?php echo $this->partial('layout/partials/default-modal'); ?>
<?php echo $this->placeholder('modals'); ?>
<?php echo $this->tracking(); ?>
<?php echo $this->partial('layout/partials/noscript'); ?>
</body>
</html>
