<?php
/**
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author      Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license     MIT License
 * @license     http://opensource.org/licenses/MIT The MIT License (MIT)
 * @link        https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright   Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
echo $this->doctype();
?>
<!--[if lt IE 9 ]>
<html class="old-ie fuelux" lang="<?php echo $this->currentLanguage(); ?>"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html class="fuelux" lang="<?php echo $this->currentLanguage(); ?>"> <!--<![endif]-->
<?php print $this->partial('layout/partials/head'); ?>
<body itemscope itemtype="http://schema.org/WebPage">
<div class="wrap">
    <?php echo $this->partial('layout/partials/header'); ?>

    <div id="page" class="has-navigation has-context col-3 clearfix">
        <?php echo $this->partial('layout/partials/left-sidebar'); ?>
        <section class="main clearfix">
            <div id="content-layout" class="content clearfix">
                <?php echo $this->partial('layout/partials/notifications'); ?>
                <?php echo $this->partial('layout/partials/main'); ?>
            </div>
            <?php echo $this->partial('layout/partials/right-sidebar'); ?>
            <?php echo $this->horizon(3); ?>
        </section>
    </div>
    <?php /* sticky footer: */ ?>
    <!-- <div id="footer-push"></div> -->
    <?php echo $this->partial('layout/partials/footer'); ?>
</div>
<?php echo $this->partial('layout/partials/default-modal'); ?>
<?php echo $this->placeholder('modals'); ?>
<?php echo $this->tracking(); ?>
<?php echo $this->partial('layout/partials/noscript'); ?>
</body>
</html>