<?php
/**
 * This file is part of Athene2.
 *
 * Copyright (c) 2013-2019 Serlo Education e.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 * you may not use this file except in compliance with the License
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @copyright Copyright (c) 2013-2019 Serlo Education e.V.
 * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache License 2.0
 * @link      https://github.com/serlo-org/athene2 for the canonical source repository
 */
echo $this->doctype();
?>
<!--[if lt IE 9 ]>    <html class="old-ie fuelux" lang="<?php echo $this->currentLanguage(); ?>"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html class="fuelux" lang="<?php echo $this->currentLanguage(); ?>"> <!--<![endif]-->
<head>
    <?php print $this->partial('layout/partials/head'); ?>
    <?php echo $this->partial('layout/partials/styles'); ?>
</head>
<!-- @deprecated -->
<!-- moved to 2-col -->
<body itemscope itemtype="http://schema.org/WebPage">
    <div class="wrap">
        <?php echo $this->partial('layout/partials/header'); ?>

        <div id="page" class="container">
            <?php echo $this->partial('layout/partials/left-sidebar'); ?>
            <section id="main">
                <div id="main-container">
                    <div id="content-layout">
                        <?php echo $this->partial('layout/partials/notifications'); ?>
                        <div id="content-container" class="content">
                            <?php echo $this->partial('layout/partials/main'); ?>
                        </div>
                    </div>
                </div>
            </section>
            <div id="ory-editor-control-popup" style="display:none;"></div>
            <?php echo $this->partial('layout/partials/banner'); ?>
            <?php echo $this->partial('layout/partials/discussions'); ?>
            <?php echo $this->partial('layout/partials/right-sidebar'); ?>
        </div>
        <?php /* sticky footer: */ ?>
        <!-- <div id="footer-push"></div> -->
        <?php echo $this->partial('layout/partials/footer'); ?>
    </div>
    <?php echo $this->partial('layout/partials/default-modal'); ?>
    <?php echo $this->placeholder('modals'); ?>
    <?php echo $this->tracking(); ?>
    <?php echo $this->partial('layout/partials/noscript'); ?>
</body>
</html>
