<?php
/**
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author      Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license     MIT License
 * @license     http://opensource.org/licenses/MIT The MIT License (MIT)
 * @link        https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright   Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
echo $this->doctype();
?>
<!--[if lt IE 9 ]>
<html class="old-ie fuelux" lang="<?php echo $this->currentLanguage(); ?>"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html class="fuelux" lang="<?php echo $this->currentLanguage(); ?>"> <!--<![endif]-->
<?php print $this->partial('layout/partials/head'); ?>
<body>
<div class="panel panel-primary" id="editor-main-panel">
    <header class="panel-heading">
        <div>
            <?php echo $this->contexter()->renderButton('right', 'btn-default'); ?>
            <div id="editor-helpers" class="btn-toolbar" role="toolbar">
                <div id="editor-actions" class="btn-group">
                    <button class="helper btn btn-success btn-labeled" data-toggle="tooltip" data-placement="bottom"
                            title="Save changes">
                        <span class="btn-label"><span class="fa fa-check"></span></span>Save
                    </button>
                    <?php if ($this->ref): ?>
                        <a class="helper btn btn-danger btn-labeled" data-toggle="tooltip" data-placement="bottom"
                           title="Reject changes" href="<?php $this->ref; ?>">
                        <span class="btn-label"><span class="fa fa-trash"></span></span>Cancel
                    </a>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </header>

    <?php echo $this->partial('layout/partials/main'); ?>

    <section id="editor-wrap">
        <div id="main" class="editor-main">
            <div class="editor-main-inner">

            </div>
        </div>
        <div id="preview" class="editor-main content-editor">
            <div id="content-layout"></div>
            <div class="editor-main-inner content">

            </div>
        </div>
    </section>
</div>

<?php echo $this->partial('layout/partials/default-modal'); ?>
<?php echo $this->headScript(); ?>
<?php echo $this->partial('layout/partials/mathjax'); ?>
<?php echo $this->inlineScript(); ?>
<?php echo $this->tracking(); ?>
</body>
</html>
