<?php
/**
 *
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author  Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license   http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
 * @link        https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */

$subject = '';
$subjectHref = '';

foreach ($this->container as $page) {
    if (! $page->isVisible() || !$this->navigation()->accept($page) || !$page->isActive(true)) {
        continue;
    }

    $subject = $page->getLabel();
    $subjectHref = $this->alias($page->getHref());
}

?>

<a class="main-headline-link" href="<?php echo $subjectHref; ?>">
<?php echo $subject; ?>
</a>