<?php
/**
 *
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author  Jonas Keinholz (jonas.keinholz@serlo.org)
 * @license LGPL-3.0
 * @license http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link        https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
$isLeaf = !empty($this->placeholder('isLeaf')->getValue());
$pagesCount = count($this->pages) + ($isLeaf ? 1 : 0);

foreach ($this->pages as $i => $page) {
    $html = [];
    $html[] = '<li>';

    $translate = is_bool($page->get('translate')) ? $page->get('translate') : $page->get('translate') === 'true';
    $label = $translate ? $this->translate($page->getLabel()) : $page->getLabel();

    // All visible items should be links as long as they aren't the last link
    if (($isLeaf || $i + 1 < $pagesCount) && $page->isVisible()) {
        $html[] = '<a href="' . $this->alias($page->getHref()) . '">';
        $html[] = '<span>' . $label . '</span>';
        $html[] = '</a>';
    } else {
        $html[] = '<span>' . $label . '</span>';
    }

    $html[] = '</li>';

    echo join(' ', $html);
}

// Show custom breadcrumbs if there are no default breadcrumbs or the given page is a leaf in the navigation
if ($isLeaf || $pagesCount === 0) {
    echo $this->placeholder('breadcrumbs');
}
