<?php
/**
 * This file is part of Athene2.
 *
 * Copyright (c) 2013-2018 Serlo Education e.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 * you may not use this file except in compliance with the License
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @copyright Copyright (c) 2013-2018 Serlo Education e.V.
 * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache License 2.0
 * @link      https://github.com/serlo-org/athene2 for the canonical source repository
 */
$isLeaf = !empty($this->placeholder('isLeaf')->getValue());
$pagesCount = count($this->pages) + ($isLeaf ? 1 : 0);

foreach ($this->pages as $i => $page) {
    $html = [];
    $html[] = '<li>';

    $translate = is_bool($page->get('translate')) ? $page->get('translate') : $page->get('translate') === 'true';
    $label = $translate ? $this->translate($page->getLabel()) : $page->getLabel();

    // All visible items should be links as long as they aren't the last link
    if (($isLeaf || $i + 1 < $pagesCount) && $page->isVisible()) {
        $html[] = '<a href="' . $this->alias($page->getHref()) . '">';
        $html[] = '<span>' . $label . '</span>';
        $html[] = '</a>';
    } else {
        $html[] = '<span>' . $label . '</span>';
    }

    $html[] = '</li>';

    echo join(' ', $html);
}

// Show custom breadcrumbs if there are no default breadcrumbs or the given page is a leaf in the navigation
if ($isLeaf || $pagesCount === 0) {
    echo $this->placeholder('breadcrumbs');
}
