<?php
/**
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author      Julian Kempff (julian.kempff@serlo.org)
 * @license     MIT License
 * @license     http://opensource.org/licenses/MIT The MIT License (MIT)
 * @link        https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright   Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */

$html = array();
$useBreadCrumbs = isset($this->useBreadCrumbs) ? $this->useBreadCrumbs : true;

foreach ($this->pages as $page) {
    $liClasses = [];
    // visibility of the sub-page
    if (!$page->isVisible() || !$this->navigation()->accept($page)) {
        continue;
    }

    if ($page->getLabel() == 'divider') {
        $html[] = '<li class="divider"></li>';
        continue;
    }


    if ($page->isActive()) {
        $liClasses[] = 'active';
    }

    $elements = '';
    if ($page->get('elements') !== null) {
        $elements = ' data-element-count="' . $page->get('elements') . '"';
    }

    $breadcrumb = ($page->isActive(true) && $useBreadCrumbs) ? 'itemscope itemtype="http://data-vocabulary.org/Breadcrumb"' : false;
    $child      = $breadcrumb ? 'itemprop="child"' : '';
    $rich       = $breadcrumb ? ' ' . $child . ' ' . $breadcrumb . ' ' : '';

    $html[] = '<li' . $rich . $elements . (count($liClasses) ? (' class="' . implode(' ', $liClasses) . '">') : '>');

    $html[] = '<a href="' . $this->alias($page->getHref()) . '"' . ($breadcrumb ? ' itemprop="url"' : '') . '>';

    if ($page->get('icon')) {
        if (stristr($page->get('icon'), 'fa-')) {
            $html[] = '<span class="' . $page->get('icon') . '"></span>';
        } else {
            $html[] = '<span class="fa fa-' . $page->get('icon') . '"></span>';
        }
    }

    if ($breadcrumb) {
        $html[] = '<span itemprop="title">' . $page->getLabel() . '</span>';
    } else {
        $html[] = '<span>' . $page->getLabel() . '</span>';
    }
    $html[] = "</a>";

    if (!empty($page->pages)) {
        $html[] = '<ul>';
        $html[] = $this->partial(
            'layout/navigation/partial/nested-navigation-list',
            array('pages' => $page->pages, 'useBreadCrumbs' => $useBreadCrumbs)
        );;
        $html[] = '</ul>';
    }

    $html[] = "</li>";
}

echo join(' ', $html);