<?php
/**
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author    Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license   http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
 * @link      https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013-2014 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
namespace Navigation;

use Zend\Navigation\Exception;
use Zend\Navigation\Navigation as ZendNavigation;
use Zend\Navigation\Page;

class Navigation extends ZendNavigation
{
    public function addPage($page)
    {
        return parent::addPage($page); // TODO: Change the autogenerated stub
    }
}
