<?php
echo nl2br(sprintf($this->translate("Dear %s,

We’re thrilled you’ve decided to write a comment or contribute to serlo.org.
To find out how to get started on editing and creating content, please visit the community homepage: https://de.serlo.org/community.
If you have any questions, problems or feedback for us, feel free to get in touch via community-de@serlo.org.

Enjoy Serlo!"), $this->user->getUsername()));
