<?php
/**
 * This file is part of Athene2.
 *
 * Copyright (c) 2013-2018 Serlo Education e.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 * you may not use this file except in compliance with the License
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @copyright Copyright (c) 2013-2018 Serlo Education e.V.
 * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache License 2.0
 * @link      https://github.com/serlo-org/athene2 for the canonical source repository
 */
?>
<?php if ($this->aggregated->count()): ?>
    <div class="sidebar-content-group">
        <ul class="nav nav-aside">
            <?php /* @var $related \RelatedContent\Result\ResultInterface */ ?>
            <?php foreach ($this->aggregated as $related): ?>
                <?php if ($related->getType() == 'category'): ?>
                    <li class="nav-aside-header">
                        <span class="h4"><?php echo $related->getTitle(); ?></span>
                    </li>
                <?php elseif ($related->getType() == 'internal'): ?>
                    <li>
                        <a href="<?php echo $related->getUrl(); ?>">
                            <?php echo $related->getTitle(); ?></a>
                    </li>
                <?php
                elseif ($related->getType() == 'external'): ?>
                    <li>
                        <a href="<?php echo $related->getUrl(); ?>">
                            <?php echo $related->getTitle(); ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
