<?php
/**
 * This file is part of Athene2.
 *
 * Copyright (c) 2013-2019 Serlo Education e.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 * you may not use this file except in compliance with the License
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @copyright Copyright (c) 2013-2019 Serlo Education e.V.
 * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache License 2.0
 * @link      https://github.com/serlo-org/athene2 for the canonical source repository
 */
?>
<?php /* @var $flag Flag\Entity\FlagInterface */ ?>
<?php $flag = $this->flag; ?>
<?php $left = 'col-md-4'; ?>
<?php $right = 'col-md-8'; ?>
<?php echo $this->pageHeader('Flag detail')->setSubtitle($flag->getId())->render(); ?>
<div class="row">
    <div class="<?php echo $left; ?>">
        <strong><?php echo $this->translate('Object'); ?></strong>
    </div>
    <div class="<?php echo $right; ?>">
        <a href="<?php echo $this->normalize()->toUrl($flag->getObject()); ?>"><?php echo $this->normalize()->toTitle($flag->getObject()); ?></a>
    </div>
</div>
<hr>
<div class="row">
    <div class="<?php echo $left; ?>">
        <strong><?php echo $this->translate('Type'); ?></strong>
    </div>
    <div class="<?php echo $right; ?>">
        <?php echo $flag->getType()->getName(); ?>
    </div>
</div>
<hr>
<div class="row">
    <div class="<?php echo $left; ?>">
        <strong><?php echo $this->translate('Timestamp'); ?></strong>
    </div>
    <div class="<?php echo $right; ?>">
        <?php echo $this->timeago()->render($flag->getTimestamp()); ?>
    </div>
</div>
<hr>
<div class="row">
    <div class="<?php echo $left; ?>">
        <strong><?php echo $this->translate('Reporter'); ?></strong>
    </div>
    <div class="<?php echo $right; ?>">
        <a href="<?php echo $this->normalize()->toUrl($flag->getReporter()); ?>"><?php echo $this->normalize()->toTitle($flag->getReporter()); ?></a>        
    </div>
</div>
<hr>
<div class="row">
    <div class="<?php echo $left; ?>">
        <strong><?php echo $this->translate('Content'); ?></strong>
    </div>
    <div class="<?php echo $right; ?>">
        <div class="panel panel-default">
            <div class="panel-body">
                <?php echo $flag->getContent(); ?>
            </div>
        </div>
    </div>
</div>