<?php
/**
 * This file is part of Athene2.
 *
 * Copyright (c) 2013-2018 Serlo Education e.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 * you may not use this file except in compliance with the License
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @copyright Copyright (c) 2013-2018 Serlo Education e.V.
 * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache License 2.0
 * @link      https://github.com/serlo-org/athene2 for the canonical source repository
 */
?>
<?php echo $this->pageHeader('Manage flags')->render(); ?>
<table class="table">
    <thead>
        <tr>
            <th><?php echo $this->translate('#');?></th>
            <th><?php echo $this->translate('Object');?></th>
            <th><?php echo $this->translate('Type');?></th>
            <th><?php echo $this->translate('Timestamp');?></th>
            <th><?php echo $this->translate('Reporter');?></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php /* @var $flag \Flag\Entity\FlagInterface */ ?>
        <?php foreach($this->flags as $flag): ?>
            <tr>
                <td>
                    <?php echo $flag->getId(); ?>
                </td>
                <td>
                    <a href="<?php echo $this->normalize()->toUrl($flag->getObject()); ?>"><?php echo $this->normalize()->toTitle($flag->getObject()); ?></a>
                </td>
                <td>
                    <?php echo $flag->getType()->getName(); ?>
                </td>
                <td>
                    <?php echo $this->timeago()->render($flag->getTimestamp());?>
                </td>
                <td>
                    <a href="<?php echo $this->normalize()->toUrl($flag->getReporter()); ?>"><?php echo $this->normalize()->toTitle($flag->getReporter()); ?></a>        
                </td>
                <td>
                    <div class="btn-group">
                        <a class="btn btn-default btn-xs" href="<?php echo $this->url('flag/detail', array('id' => $flag->getId())); ?>"><span class="fa fa-search"></span></a>
                        <?php if ($this->isGranted('flag.purge', $flag)): ?>
                            <?php $trashbutton = '<button class="btn btn-danger btn-xs"><span class="fa fa-trash"></span></button>';
                            $this->form->setAttribute('action', $this->url('flag/remove', ['id' => $flag->getId()]));
                            echo $this->twigPartial('common/csrfform', array('form' => $this->form, 'sendbutton' => $trashbutton));
                            ?>
                        <?php endif; ?>
                    </div>
                </td>
            </tr>
            <?php ?>
        <?php endforeach; ?>
    </tbody>
</table>