<?php
/**
 * This file is part of Athene2.
 *
 * Copyright (c) 2013-2018 Serlo Education e.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 * you may not use this file except in compliance with the License
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @copyright Copyright (c) 2013-2018 Serlo Education e.V.
 * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache License 2.0
 * @link      https://github.com/serlo-org/athene2 for the canonical source repository
 */
?>
<?php echo $this->pageHeader('Roles')->render(); ?>
<div class="list-group">
    <?php foreach ($this->roles as $role): ?>
        <a class="list-group-item"
           href="<?php echo $this->url('authorization/role/show', array('role' => $role->getId())); ?>">
            <h4 class="list-group-item-heading">
                <span class="badge pull-right"><?php echo $role->getUsers()->count(); ?></span>
                <?php echo $role->getName(); ?>
            </h4>

            <p class="list-group-item-text"><?php echo $role->getDescription(); ?></p>
        </a>
    <?php endforeach; ?>
    <?php if($this->isGranted('authorization.role.create')): ?>
        <div class="list-group-item clearfix">
            <a class="btn btn-success pull-right" href="<?php echo $this->url('authorization/role/create'); ?>">
                <span class="fa fa-plus"></span>
                <?php echo $this->translate('role'); ?>
            </a>
        </div>
    <?php endif; ?>
</div>