<?php
/**
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author    Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license   http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
 * @link      https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013-2014 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
?>
<?php echo $this->pageHeader('Role')->setSubtitle($this->role->getName())->render(); ?>
<?php if ($this->isGranted('authorization.identity.grant.role', $this->role)): ?>
    <div class="pull-right">
        <a class="btn btn-success btn-xs"
           href="<?php echo $this->url('authorization/role/user/add', ['role' => $this->role->getId()]); ?>"> <span
                class="fa fa-plus"></span> </a>
    </div>
<?php endif; ?>
<h3><?php echo $this->translate('Users'); ?></h3>
<hr/>
<ul class="list-group">
    <?php foreach ($this->users as $user): ?>
        <li class="list-group-item">
            <?php if ($this->isGranted('authorization.identity.revoke.role', $this->role)): ?>
                <?php $form = $this->authForm()->getRemoveUserForm($user->getUsername(), $this->role->getId());
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    echo $this->formRow($form->get('authorization_remove_user_csrf_' . $user->getUsername()));
                    echo $this->formRow($form->get('user')); ?>
                    <button type="submit" class="btn btn-danger btn-xs">
                        <span class="fa fa-minus"></span>
                    </button>
                <?php echo $this->form()->closeTag();?>
            <?php endif; ?>
            <?php echo $user->getUsername() ?>
        </li>
    <?php endforeach; ?>
</ul>
<?php if ($this->isGranted('authorization.role.grant.permission')): ?>
    <div class="pull-right">
        <a class="btn btn-success btn-xs"
           href="<?php echo $this->url('authorization/role/permission/add', ['role' => $this->role->getId()]); ?>">
            <span class="fa fa-plus"></span> </a>
    </div>
<?php endif; ?>
<h3><?php echo $this->translate('Permissions'); ?></h3>
<hr/>
<div class="list-group">
    <?php foreach ($this->role->getPermissions() as $permission): ?>
        <div class="list-group-item">
            <?php echo $permission->getName(); ?>
            <small>
                (
                <?php if ($permission->getParameter('instance')): ?>
                    <?php echo $permission->getParameter('instance'); ?>
                <?php else: ?>
                    <?php echo $this->translate('Global'); ?>
                <?php endif; ?>
                )
            </small>
            <?php if ($this->isGranted('authorization.role.revoke.permission')): ?>
                <?php $form = $this->authForm()->getRemovePermissionForm($this->role->getId(), $permission->getId());
                $form->prepare();
                echo $this->form()->openTag($form);
                echo $this->formRow($form->get('authorization_remove_permission_csrf_'
                    . $this->role->getId() . '_' . $permission->getId()));
                echo $this->formRow($form->get('role'));
                echo $this->formRow($form->get('permission')); ?>
                <button type="submit" class="btn btn-danger btn-xs">
                    <span class="fa fa-minus"></span>
                </button>
                <?php echo $this->form()->closeTag();?>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
</div><h3><?php echo $this->translate('Inherits from'); ?></h3>
<hr/>
<div class="list-group">
    <?php foreach ($this->role->getChildren() as $child): ?>
        <a class="list-group-item" href="<?php echo $this->url(
            'authorization/role/show',
            ['role' => $child->getId()]
        ); ?>"><?php echo $child->getName(); ?></a>
    <?php endforeach; ?>
</div>