<?php
/**
 * This file is part of Athene2.
 *
 * Copyright (c) 2013-2019 Serlo Education e.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 * you may not use this file except in compliance with the License
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @copyright Copyright (c) 2013-2019 Serlo Education e.V.
 * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache License 2.0
 * @link      https://github.com/serlo-org/athene2 for the canonical source repository
 */
?>
<?php echo $this->pageHeader('Role')->setSubtitle($this->role->getName())->render(); ?>
<?php if ($this->isGranted('authorization.identity.grant.role', $this->role)): ?>
    <div class="pull-right">
        <a class="btn btn-success btn-xs"
           href="<?php echo $this->url('authorization/role/user/add', ['role' => $this->role->getId()]); ?>"> <span
                class="fa fa-plus"></span> </a>
    </div>
<?php endif; ?>
<h3><?php echo $this->translate('Users'); ?></h3>
<hr/>
<ul class="list-group">
    <?php foreach ($this->users as $user): ?>
        <li class="list-group-item">
            <?php if ($this->isGranted('authorization.identity.revoke.role', $this->role)): ?>
                <?php $trashbutton = '<button type="submit" class="btn btn-danger btn-xs">
                        <span class="fa fa-minus"></span>
                    </button>'; ?>
                <?php $this->removeUserForm->setAttribute('action', $this->url('authorization/role/user/remove', ['role' => $this->role->getId()]));?>
                <?php $this->removeUserForm->setAttribute('class', 'pull-right'); ?>
                <?php echo $this->twigPartial('common/csrfform', [
                        'form' => $this->removeUserForm,
                        'sendbutton' => $trashbutton,
                        'additionalFields' => [
                            'user' => '<input type="hidden" name="user" value="'.$user->getUsername().'"/>'
                        ]
                    ]); ?>
            <?php endif; ?>
            <?php echo $user->getUsername() ?>
        </li>
    <?php endforeach; ?>
</ul>
<?php if ($this->isGranted('authorization.role.grant.permission')): ?>
    <div class="pull-right">
        <a class="btn btn-success btn-xs"
           href="<?php echo $this->url('authorization/role/permission/add', ['role' => $this->role->getId()]); ?>">
            <span class="fa fa-plus"></span> </a>
    </div>
<?php endif; ?>
<h3><?php echo $this->translate('Permissions'); ?></h3>
<hr/>
<div class="list-group">
    <?php foreach ($this->role->getPermissions() as $permission): ?>
        <div class="list-group-item">
            <?php echo $permission->getName(); ?>
            <small>
                (
                <?php if ($permission->getParameter('instance')): ?>
                    <?php echo $permission->getParameter('instance'); ?>
                <?php else: ?>
                    <?php echo $this->translate('Global'); ?>
                <?php endif; ?>
                )
            </small>
            <?php if ($this->isGranted('authorization.role.revoke.permission')): ?>
                <?php $trashbutton = '<button type="submit" class="btn btn-danger btn-xs">
                        <span class="fa fa-minus"></span>
                    </button>'; ?>
                <?php $this->removePermissionForm->setAttribute('action', $this->url('authorization/role/permission/remove', ['role' => $this->role->getId(), 'permission' => $permission->getId()]));?>
                <?php $this->removePermissionForm->setAttribute('class', 'pull-right'); ?>
                <?php echo $this->twigPartial('common/csrfform', array('form' => $this->removePermissionForm, 'sendbutton' => $trashbutton)); ?>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
</div><h3><?php echo $this->translate('Inherits from'); ?></h3>
<hr/>
<div class="list-group">
    <?php foreach ($this->role->getChildren() as $child): ?>
        <a class="list-group-item" href="<?php echo $this->url(
            'authorization/role/show',
            ['role' => $child->getId()]
        ); ?>"><?php echo $child->getName(); ?></a>
    <?php endforeach; ?>
</div>