<?php
/**
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author    Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license   LGPL-3.0
 * @license   http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link      https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013-2014 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
?>
<div class="page-header">
    <h1><?php echo $this->translate('Blogs'); ?></h1>
</div>
<div class="list-group">
    <?php foreach ($this->blogs as $blog): ?>
        <a class="list-group-item"
           href="<?php echo $this->url('blog/view',
               array('id' => $blog->getId())); ?>"><?php echo $blog->getName(); ?></a>
    <?php endforeach; ?>
</div>