<?php
/**
 *
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author	Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license   http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
 * @link		https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
?>
<?php echo $this->pageHeader('Trashed learning resources')->setSubtitle($this->subject->getName())->render(); ?>
<table class="table table-striped">
	<thead>
		<tr>
			<th><?php echo $this->translate('Title'); ?></th>
			<th><?php echo $this->translate('Type'); ?></th>
			<th><?php echo $this->translate('Action'); ?></th>
		</tr>
	</thead>
	<tbody>
        <?php foreach($this->entities as $entity): ?>
            <tr>
                <td><a href="<?php echo $this->url($entity->getRouteName(), $entity->getRouteParams()); ?>"><?php echo $entity->getTitle(); ?></a></td>
                <td><?php echo $entity->getType(); ?></td>
                <td>
                    <div class="btn-group">
                    <?php if ($this->isGranted('entity.restore', $this->subject)): ?>
					<a class="btn btn-success btn-xs"
						href="<?php echo $this->url('uuid/restore', array('id' => $entity->getId())); ?>"><span
						class="fa fa-refresh"></span></a>
                    <?php endif; ?>
                    <?php if ($this->isGranted('entity.purge', $this->subject)): ?>
                        <?php $trashbutton = '<button class="dialog btn btn-danger btn-xs"
                            data-content="'.$this->translate('Do you really want to purge this item? It and all references to it will be lost forever!').'"
                            data-type="danger">
                                <span class="fa fa-fire"></span>
                            </button>';
                            echo $this->twigPartial('common/csrfform', array('form' => $this->uuidForm()->getPurgeForm($entity->getId()), 'sendbutton' => $trashbutton));
                        ?>
                    <?php endif; ?>
				</div>
            </td>
		</tr>
        <?php endforeach; ?>
	</tbody>
</table>
