<?php
/**
 * This file is part of Athene2.
 *
 * Copyright (c) 2013-2018 Serlo Education e.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 * you may not use this file except in compliance with the License
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @copyright Copyright (c) 2013-2018 Serlo Education e.V.
 * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache License 2.0
 * @link      https://github.com/serlo-org/athene2 for the canonical source repository
 */
?>
<?php echo $this->pageHeader('Unrevised learning resources')->setSubtitle($this->subject->getName())->append($this->contexter()->renderButton('right'))->render(); ?>
<table class="table table-striped">
    <thead>
        <tr>
            <th><?php echo $this->translate('Title'); ?></th>
            <th><?php echo $this->translate('Revision'); ?></th>
            <th><?php echo $this->translate('Type'); ?></th>
            <th><?php echo $this->translate('Timestamp'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php $previousEntityId = -1; ?>
        <?php /** @var \Entity\Entity\RevisionInterface $revision */ ?>
        <?php foreach ($this->revisions as $revision): ?>
        <?php $normalized = $this->normalize($revision); ?>
        <?php /** @var \Normalizer\Entity\NormalizedInterface $entity */ ?>
        <?php $entity = $this->normalize($revision->getRepository()); ?>
        <tr>
            <td style="width:30%">
                <?php if ($entity->getId() !== $previousEntityId): ?>
                    <?php echo htmlspecialchars($entity->getTitle()); ?>
                <?php endif; ?>
            </td>
            <td><a href="<?php echo $this->url($normalized->getRouteName(), $normalized->getRouteParams()); ?>"><?php echo $normalized->getId(); ?></a></td>
            <td><?php echo $this->translate($normalized->getType()); ?></td>
            <td><?php echo $this->timeago()->render($normalized->getMetadata()->getCreationDate()); ?></td>
        </tr>
        <?php $previousEntityId = $entity->getId(); ?>
        <?php endforeach; ?>
    </tbody>
</table>
