<?php
/**
 * This file is part of Athene2.
 *
 * Copyright (c) 2013-2018 Serlo Education e.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 * you may not use this file except in compliance with the License
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @copyright Copyright (c) 2013-2018 Serlo Education e.V.
 * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache License 2.0
 * @link      https://github.com/serlo-org/athene2 for the canonical source repository
 */
?>
<?php if ($this->pageCount): ?>
    <div class="text-center">
        <ul class="pagination">
            <!-- Previous page link -->
            <?php $params = $this->params ? : [];
            $this->options = $this->options ? : [];
            if (isset($this->previous)): ?>
                <li>
                    <?php $options = array_merge_recursive($this->options, ['query' => ['page' => $this->previous]]); ?>
                    <a href="<?php echo $this->url($this->route, $params, $options); ?>">
                        <span class="fa fa-chevron-left"></span>
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        <span class="fa fa-chevron-left"></span>
                    </a>
                </li>
            <?php endif; ?>
            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li>
                        <?php $options = array_merge_recursive($this->options, ['query' => ['page' => $page]]); ?>
                        <a href="<?php echo $this->url($this->route, $params, $options);?>">
                            <?php echo $page; ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="active">
                        <a href="#"><?php echo $page; ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li>
                    <?php $options = array_merge_recursive($this->options, ['query' => ['page' => $this->next]]); ?>
                    <a href="<?php echo $this->url($this->route, $params, $options); ?>">
                        <span class="fa fa-chevron-right"></span>
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        <span class="fa fa-chevron-right"></span>
                    </a>
                </li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>