<?php echo $this->partial('layout/partials/mathjax'); ?>
<?php echo $this->headScript(); ?>
<?php echo $this->inlineScript(); ?>
<?php if ($this->prerelease()): ?>
  <script src="https://unpkg.com/@serlo-org/athene2-assets@0/dist/commons.js" type="text/javascript"></script>
  <script src="https://unpkg.com/@serlo-org/athene2-assets@0/dist/editor.js" type="text/javascript"></script>
<?php else: ?>
  <script src="/assets/libs.js" type="text/javascript"></script>
  <script src="/assets/editor_scripts.js" type="text/javascript"></script>
<?php endif; ?>
<?php echo $this->tracking(); ?>
