<?php
/**
 * This file is part of Athene2.
 *
 * Copyright (c) 2013-2019 Serlo Education e.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 * you may not use this file except in compliance with the License
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @copyright Copyright (c) 2013-2019 Serlo Education e.V.
 * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache License 2.0
 * @link      https://github.com/serlo-org/athene2 for the canonical source repository
 */
?>
<svg xmlns="http://www.w3.org/2000/svg" width="90" height="90" fill="#95BC1A"><path d="M66.4 39.5a11 11 0 0 0-21.7-2.1A11 11 0 0 0 23 40.7c1.2 12.6 21.5 24.2 21.5 24.2s20.7-11.6 21.9-24.2v-1.2zM44.3.5h1.5V15h-1.5zm0 74.5h1.5v14.5h-1.5zM75 44.3h14.5v1.5H75zm-74.5 0H15v1.5H.5zm66.2-20l-1-1L75.8 13l1 1zM23.3 65.6l1 1L14.2 77l-1-1zm0-41.2L13 14l1-1 10.3 10.2zm43.3 41.2L77 76l-1 1-10.3-10.2z"/></svg>
