<?php
/**
 *
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author  Jonas Keinholz (jonas.keinholz@serlo.org)
 * @license   http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
 * @link        https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
echo $this->doctype();
?>
<html class="fuelux" lang="<?php echo $this->currentLanguage(); ?>">
<?php echo $this->partial('layout/partials/head'); ?>

<body class="serlo-home serlo-de-home" itemscope itemtype="http://schema.org/WebPage">
<div class="wrap">
    <header id="header">
        <?php echo $this->partial('layout/partials/top-bar'); ?>

        <div class="container-fluid">
            <nav id="header-nav">
                <div id="mobile-nav-toggle">
                    <button>
                        <span class="sr-only"><?php echo $this->translate('Toggle navigation') ?></span>
                        <i class="fa fa-fw fa-bars"></i>
                    </button>
                    <?php echo $this->brand()->getLogo(); ?>
                    <?php echo $this->brand()->getBrand(); ?>
                    <span class="subject-title hidden-xs"><?php echo $this->navigation('default_navigation')
                            ->menu()
                            ->setPartial('layout/navigation/partial/active-subject')
                            ->setOnlyActiveBranch(true)
                            ->setMinDepth(0)
                            ->setMaxDepth(0)
                            ->render();
                        ?></span>
                </div>

                <div id="mobile-nav-right">
                    <ul class="authentification nav navbar-nav">
                        <li class="dropdown">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#" aria-expanded="false">
                                <span class="fa fa-user"></span>
                            </a>
                            <?php
                            echo $this->navigation('top_auth_navigation')
                                ->menu()
                                ->setUlClass('dropdown-menu dropdown-menu-right')
                                ->setPartial('layout/navigation/horizontal')
                                ->render();
                            ?>
                        </li>
                    </ul>
                    <ul class="notifications nav navbar-nav">
                        <?php echo $this->notifications()->render(); ?>
                    </ul>
                </div>
            </nav>

            <div id="mobile-nav"></div>

            <?php if (empty($this->placeholder('hideSubjectNav')->getValue())): ?>
                <nav id="subject-nav">
                    <div id="subject-nav-wrapper">
                        <div class="subject-nav-center">
                            <div class="pull-right controls">
                                <?php echo $this->placeholder('controls'); ?>
                            </div>
                            <ol id="breadcrumbs">
                            </ol>
                        </div>
                        <?php echo $this->partial('layout/partials/search'); ?>
                    </div>
                </nav>
            <?php endif; ?>
        </div>
    </header>

    <div id="page">
        <section class="clearfix">
            <div id="content-layout" class="clearfix">
                <?php echo $this->partial('layout/partials/notifications'); ?>
                <div class="home-header">
                    <?php echo $this->brand()->getLogo(); ?>
                    <?php echo $this->brand()->getBrand(); ?>
                    <div class="header-text">Die freie Lernplattform</div>
                </div>

                <div class="home-row col-lg-1"></div>
                <div class="home-row col-md-12 col-lg-10">
                    <div class="home-row home-subject-row">
                        <div class="home-column col-md-3 col-xs-6 container">
                            <a class="home-emph-link" href="/mathe">
                                <div class="row">
                                    <div class="col-xs-12 home-subject-symbol">
                                        <?php echo $this->partial('layout/de/home-math-symbol');?>
                                    </div>
                                </div>
                                <div class="row home-subject-column">
                                    <div class="col-xs-12">
                                        <span class="home-subject">
                                            Mathematik <br> lernen
                                            <i class="fa fa-arrow-circle-right home-subject"></i>
                                        </span>
                                    </div>
                                </div>
                            </a>
                        </div>
                        <div class="home-column col-md-3 col-xs-6 container">
                            <a class="home-emph-link" href="/abc">
                                <div class="row">
                                    <div class="col-xs-12 home-subject-symbol">
                                        <?php echo $this->partial('layout/de/home-abc-symbol');?>
                                    </div>
                                </div>
                                <div class="row home-subject-column">
                                    <div class="col-xs-12">
                                        <span class="home-subject">
                                            Alphabetisierung <br> für Neusprachler
                                            <i class="fa fa-arrow-circle-right home-subject"></i>
                                        </span>
                                    </div>
                                </div>
                            </a>
                        </div>
                        <div class="home-column col-xs-6 col-md-3 container">
                            <a class="home-emph-link" href="/nachhaltigkeit">
                                <div class="row home-subject-column">
                                    <div class="col-xs-12 home-subject-symbol">
                                        <?php echo $this->partial('layout/de/home-sustain-symbol');?>
                                    </div>
                                </div>
                                <div class="row home-subject-column">
                                    <div class="col-xs-12">
                                        <span class="home-subject">
                                            Nachhaltigkeit <br> lernen
                                            <i class="fa fa-arrow-circle-right home-subject"></i>
                                        </span>
                                    </div>
                                </div>
                            </a>
                        </div>
                        <div class="home-column col-md-3 col-xs-6 container">
                            <a class="home-emph-link" href="/biologie">
                                <div class="row">
                                    <div class="col-xs-12 home-subject-symbol">
                                        <?php echo $this->partial('layout/de/home-bio-symbol');?>
                                    </div>
                                </div>
                                <div class="row home-subject-column">
                                    <div class="col-xs-12">
                                        <span class="home-subject">
                                            Biologie <br> lernen
                                            <i class="fa fa-arrow-circle-right home-subject"></i>
                                        </span>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="home-row col-lg-1"></div>

                <div class="home-serlo-row home-row">
                    <div class="home-column home-col-md-1"></div>
                    <div class="home-column home-col-md-4">
                        <p><h2>Hauptpartner</h2></p>
                        <a href="/21456">
                            <img src="/assets/images/de/home_logo_tum.svg" alt="Technische Universität München"/>
                        </a>
                        <a href="/21456">
                            <img src="/assets/images/de/home_logo_sauer.png" alt="Hans Sauer Stiftung"/>
                        </a>
                        <a href="/21456">
                            <img src="/assets/images/de/home_logo_wiki.svg" alt="Wikimedia Deutschland"/>
                        </a>
                    </div>
                    <div class="home-column home-col-md-1"></div>
                </div>

                <div class="home-blue-row home-row">
                    <div class="home-column" style="color: white">
                        <p>Serlo bietet einfache Erklärungen, tausende <br> Aufgaben und Musterlösungen komplett <br> kostenlos.
                            Unsere Vision ist es, hochwertige <br> Bildung weltweit frei verfügbar zu machen. <br> Dafür bauen
                            wir eine Wikipedia für's Lernen.</p>
                        <a class="home-emph-link" href="/18922">Mehr erfahren <i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div>

                <div class="home-launch-img-row home-row"></div>

                <div class="home-community-wrapper">
                    <div class="home-community-row home-row">
                        <div class="home-column home-col-md-3">
                            <img src="/assets/images/home_participate.svg"/>

                            <h2>Serlo ist ein Wiki:</h2>

                            <p>
                                Hilf uns Bildung frei verfügbar zu machen und werde Teil der Online-Community von Serlo.
                                Wir suchen Lehrer und Hobbydidaktiker mit Begeisterung für ihr Fach.
                            </p>
                            <img src="/assets/images/home_commons.svg"/><br/>
                            <a href="/19869" class="home-hide-md home-emph-link">Mitmachen <i class="fa fa-arrow-circle-right"></i></a>
                        </div>
                        <div class="home-column home-col-md-3">
                            <img src="/assets/images/home_donate.svg"/>

                            <h2>Serlo ist eine Non-Profit-Organisation:</h2>

                            <p class="text-center">
                                Softwareentwicklung, Betreuung der Ehrenamtlichen und Aufbau der Organisation kosten
                                Geld. Wir freuen uns sehr, wenn Sie Serlo mit einer Spende unterstützen.
                            </p>
                            <a href="/21565" class="home-hide-md home-emph-link">Spenden <i class="fa fa-arrow-circle-right"></i></a>
                        </div>
                    </div>

                    <div class="home-community-link-row home-row">
                        <div class="home-column home-col-md-3">
                            <a href="/19869" class="home-emph-link home-show-md">Mitmachen <i class="fa fa-arrow-circle-right"></i></a>
                        </div>
                        <div class="home-column home-col-md-3">
                            <a href="/21565" class="home-emph-link home-show-md">Spenden <i class="fa fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <div id="footer-push"></div>
</div>

<?php echo $this->partial('layout/partials/footer'); ?>
<?php echo $this->partial('layout/partials/default-modal'); ?>
<?php echo $this->placeholder('modals'); ?>
<?php echo $this->tracking(); ?>
<?php echo $this->partial('layout/partials/noscript'); ?>
</body>
</html>