<?php
/**
 *
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author  Jonas Keinholz (jonas.keinholz@serlo.org)
 * @license   http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
 * @link        https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
echo $this->doctype();
?>
<html class="fuelux" lang="<?php echo $this->currentLanguage(); ?>">
<?php echo $this->partial('layout/partials/head'); ?>

<body class="serlo-home serlo-de-home" itemscope itemtype="http://schema.org/WebPage">
<div class="wrap">
    <header id="header">
        <?php echo $this->partial('layout/partials/top-bar'); ?>

        <div class="container-fluid">
            <nav id="header-nav">
                <div id="mobile-nav-toggle">
                    <button>
                        <span class="sr-only"><?php echo $this->translate('Toggle navigation') ?></span>
                        <i class="fa fa-fw fa-bars"></i>
                    </button>
                    <?php echo $this->brand()->getLogo(); ?>
                    <?php echo $this->brand()->getBrand(); ?>
                    <span class="subject-title hidden-xs"><?php echo $this->navigation('default_navigation')
                            ->menu()
                            ->setPartial('layout/navigation/partial/active-subject')
                            ->setOnlyActiveBranch(true)
                            ->setMinDepth(0)
                            ->setMaxDepth(0)
                            ->render();
                        ?></span>
                </div>

                <div id="mobile-nav-right">
                    <ul class="authentification nav navbar-nav">
                        <li class="dropdown">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#" aria-expanded="false">
                                <span class="fa fa-user"></span>
                            </a>
                            <?php
                            echo $this->navigation('top_auth_navigation')
                                ->menu()
                                ->setUlClass('dropdown-menu dropdown-menu-right')
                                ->setPartial('layout/navigation/horizontal')
                                ->render();
                            ?>
                        </li>
                    </ul>
                    <ul class="notifications nav navbar-nav">
                        <?php echo $this->notifications()->render(); ?>
                    </ul>
                </div>
            </nav>

            <div id="mobile-nav"></div>

            <?php if (empty($this->placeholder('hideSubjectNav')->getValue())): ?>
                <nav id="subject-nav">
                    <div id="subject-nav-wrapper">
                        <div class="subject-nav-center">
                            <div class="pull-right controls">
                                <?php echo $this->placeholder('controls'); ?>
                            </div>
                            <ol id="breadcrumbs">
                            </ol>
                        </div>
                        <?php echo $this->partial('layout/partials/search'); ?>
                    </div>
                </nav>
            <?php endif; ?>
        </div>
    </header>

    <div id="page">
        <section class="clearfix">
            <div id="content-layout" class="clearfix">
                <?php echo $this->partial('layout/partials/notifications'); ?>
                <div class="home-header">
                    <?php echo $this->brand()->getLogo(); ?>
                    <?php echo $this->brand()->getBrand(); ?>
                    <div class="header-text">Die freie Lernplattform</div>
                </div>

                <div class="col-md-12 col-lg-10 col-lg-offset-1">
                    <div class="home-row home-subject-row">
                        <div class="home-column col-lg-3 col-sm-6 container">
                            <a class="home-emph-link" href="/mathe">
                                <div class="row">
                                    <div class="col-xs-12 home-subject-symbol">
                                        <?php echo $this->partial('layout/de/home-math-symbol');?>
                                    </div>
                                </div>
                                <div class="row home-subject-column">
                                    <div class="col-xs-12">
                                        <span class="home-subject">
                                            Mathematik <br> lernen
                                            <i class="fa fa-arrow-circle-right home-subject"></i>
                                        </span>
                                    </div>
                                </div>
                            </a>
                        </div>
                        <div class="home-column col-lg-3 col-sm-6 container">
                            <a class="home-emph-link" href="/abc">
                                <div class="row">
                                    <div class="col-xs-12 home-subject-symbol">
                                        <?php echo $this->partial('layout/de/home-abc-symbol');?>
                                    </div>
                                </div>
                                <div class="row home-subject-column">
                                    <div class="col-xs-12">
                                        <span class="home-subject">
                                            Alphabetisierung <br> für Neusprachler
                                            <i class="fa fa-arrow-circle-right home-subject"></i>
                                        </span>
                                    </div>
                                </div>
                            </a>
                        </div>
                        <div class="home-column col-sm-6 col-lg-3 container">
                            <a class="home-emph-link" href="/nachhaltigkeit">
                                <div class="row home-subject-column">
                                    <div class="col-xs-12 home-subject-symbol">
                                        <?php echo $this->partial('layout/de/home-sustain-symbol');?>
                                    </div>
                                </div>
                                <div class="row home-subject-column">
                                    <span class="home-subject">
                                        Nachhaltigkeit <br> lernen
                                        <i class="fa fa-arrow-circle-right home-subject"></i>
                                    </span>
                                </div>
                            </a>
                        </div>
                        <div class="home-column col-lg-3 col-sm-6 container">
                            <a class="home-emph-link" href="/biologie">
                                <div class="row">
                                    <div class="col-xs-12 home-subject-symbol">
                                        <?php echo $this->partial('layout/de/home-bio-symbol');?>
                                    </div>
                                </div>
                                <div class="row home-subject-column">
                                    <div class="col-xs-12">
                                        <span class="home-subject">
                                            Biologie <br> lernen
                                            <i class="fa fa-arrow-circle-right home-subject"></i>
                                        </span>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="home-about-wrapper">
                <div class="home-row home-about-row">
                    <div class="col-md-6">
                        <div class="home-header">
                            <?php echo $this->brand()->getLogo(); ?>
                            <?php echo $this->brand()->getBrand(); ?>
                        </div>
                        <p>Die freie Lernplattform serlo.org bietet einfache <br> Erklärungen, Kurse und tausende Aufgaben <br> mit Musterlösungen für Schüler und Studenten. <br>
                            Unsere Vision ist es, hochwertige Bildung <br> weltweit frei verfügbar zu machen. <br> </p>
                        <a class="home-emph-link" href="/18922">Mehr erfahren <i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                    <div class="col-md-6 home-serlo-learn">
                        <div class="home-learn-wrapper">
                            <div class="col-xs-6">
                                <img class="icon" src="/assets/images/icon_selbststaendig"/>
                            </div>
                            <div class="col-xs-6 text">
                                Selbstständig lernen, <br>im eigenen Tempo
                            </div>
                        </div>
                        <div>
                            <div class="col-xs-6">
                                <img class="icon" src="/assets/images/icon_frei"/>
                            </div>
                            <div class="col-xs-6 text">
                                Komplett kostenlos <br>und ohne Werbung
                            </div>
                        </div>
                    </div>
                    <div class="home-partner-row home-column home-col-md-6">
                        <p><h2>Hauptpartner</h2></p>
                        <a href="/21456">
                            <img src="/assets/images/de/home_logo_tum.svg" alt="Technische Universität München"/>
                        </a>
                        <a href="/21456">
                            <img src="/assets/images/de/home_logo_eu.png" alt="Europäische Kommission"/>
                        </a>
                        <a href="/21456">
                            <img src="/assets/images/de/home_logo_lmu.svg" alt="Ludwig-Maximilians-Universität München"/>
                        </a>
                        <a href="/21456">
                            <img src="/assets/images/de/home_logo_sauer.png" alt="Hans Sauer Stiftung"/>
                        </a>
                        <a href="/21456">
                            <img src="/assets/images/de/home_logo_wiki.svg" alt="Wikimedia Deutschland"/>
                        </a>
                    </div>
                </div>
                </div>
                <div class="home-calls-wrapper">
                    <div class="home-calls-header">
                        <h2>Serlo.org ist die Wikipedia für's Lernen<h2>
                    </div>
                    <div class="home-texts-row home-row">
                        <div class="home-col-md-3">
                            <p>Wir suchen Lehrer und Hobby-Lehrer mit Begeisterung für ihr Fach.
                                Werden Sie Autor auf serlo.org, erstellen Sie neue Inhalte und helfen Sie uns,
                                die Qualität der Lernplattform zu sichern.</p>
                        </div>
                        <div class="home-col-md-3">
                            <p>Wir bieten zahlreiche spannende Aufgaben aus den Bereichen
                                Softwareentwicklung, Redaktion und NGO-Management.</p>
                        </div>
                    </div>
                    <div class="home-links-row home-row">
                        <div class="home-col-md-3">
                            <a href="/mitmachen" class="home-emph-link">
                                Zur Startseite für Autoren <i class="fa fa-arrow-circle-right"></i>
                            </a>
                        </div>
                        <div class="home-col-md-3">
                            <a href="/jobs" class="home-emph-link">
                                Jobs und Engagement <i class="fa fa-arrow-circle-right"></i>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="home-row home-principle-row home-column"></div>
                <div class="home-launch-img-row home-row"></div>

                <div class="home-calls-wrapper">
                    <div class="home-calls-header">
                        <h2>Werde Teil unserer Bewegung für freie Bildung<h2>
                    </div>
                    <div class="home-texts-row home-row">
                        <div class="home-col-md-3">
                            <p>Softwareentwicklung und Lerninhalte erstellen kostet Geld. Wir freuen uns sehr,
                                wenn sie Serlo mit einer Spende unterstützen.</p>
                        </div>
                        <div class="home-col-md-3">
                            <p>Bildung gehört uns allen! Werden Sie Mitglied in unserer Organisation
                                Serlo Education e.V. und so zum “Mitherausgeber” der freien Lernplattform.</p>
                        </div>
                    </div>
                    <div class="home-links-row home-row">
                        <div class="home-col-md-3">
                            <a class="home-emph-link" href="/spenden">
                                Spenden <i class="fa fa-arrow-circle-right"></i>
                            </a>
                        </div>
                        <div class="home-col-md-3">
                            <a class="home-emph-link" href="/beitreten">
                                Mitglied werden <i class="fa fa-arrow-circle-right"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="home-column heart"> <img src="assets/images/home_donate.svg" alt="heart"> </div>
            </div>
        </section>
    </div>
    <div id="footer-push"></div>
</div>

<?php echo $this->partial('layout/partials/footer'); ?>
<?php echo $this->partial('layout/partials/default-modal'); ?>
<?php echo $this->placeholder('modals'); ?>
<?php echo $this->tracking(); ?>
<?php echo $this->partial('layout/partials/noscript'); ?>
</body>
</html>
