<?php
/**
 * This file is part of Athene2.
 *
 * Copyright (c) 2013-2018 Serlo Education e.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 * you may not use this file except in compliance with the License
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @copyright Copyright (c) 2013-2018 Serlo Education e.V.
 * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache License 2.0
 * @link      https://github.com/serlo-org/athene2 for the canonical source repository
 */
?>
<?php /* @var $current \Instance\Entity\InstanceInterface */ ?>
<?php $current = $this->current; ?>
<?php /* @var $instances \Instance\Entity\InstanceInterface[] */ ?>
<?php $instances = $this->instances; ?>
<ul class="nav navbar-nav pull-right">
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <?php echo $current->getName(); ?> <span class="caret"></span>
        </a>
        <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
            <?php foreach ($instances as $instance): ?>
                <li role="presentation">
                <li role="presentation">
                    <a role="menuitem" tabindex="-1" href="<?php echo $this->url('instance/switch', ['instance' => $instance->getId()]); ?>">
                        <?php echo $instance->getName(); ?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </li>
</ul>