<?php $blog = $this->post->getBlog(); ?>
<?php $blogUrl = $this->normalize()->toUrl($blog); ?>
<?php $this->normalize()->headTitle($this->post); ?>
<article>
    <header class="page-header">
        <ul class="nav nav-pills pull-left">
            <li>
                <a href="<?php echo $blogUrl;?>"><span class="glyphicon glyphicon-chevron-left"></span></a>
            </li>
        </ul>
        <h1>
            <?php echo $this->post->getTitle(); ?>
            <small>
                <?php echo $this->translate(sprintf(
                    'by %s <small>%s</small>',
                    $this->post->getAuthor()->getUsername(),
                    $this->timeago()->render($this->post->getTimestamp())
                )); ?>
            </small>
        </h1>
    </header>
    <?php echo $this->markdown()->toHtml($this->post->getContent()); ?>
</article>