<?php
/**
 *
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author  Jonas Keinholz (jonas.keinholz@serlo.org)
 * @license   http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
 * @link        https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
echo $this->doctype();
?>
<html class="fuelux" lang="<?php echo $this->currentLanguage(); ?>">
<?php echo $this->partial('layout/partials/head'); ?>

<body class="serlo-home serlo-en-home" itemscope itemtype="http://schema.org/WebPage">
<div class="wrap">
    <header id="header">
        <?php echo $this->partial('layout/partials/top-bar'); ?>
        <div class="container-fluid">
            <nav id="header-nav">
                <div id="mobile-nav-toggle">

                    <button>
                        <span class="sr-only"><?php echo $this->translate('Toggle navigation') ?></span>
                        <i class="fa fa-fw fa-bars"></i>
                    </button>

                    <?php echo $this->brand()->getLogo(); ?>
                    <?php echo $this->brand()->getBrand(); ?>

                    <span class="subject-title hidden-xs">
                        <?php echo $this->navigation('default_navigation')
                            ->menu()
                            ->setPartial('layout/navigation/partial/active-subject')
                            ->setOnlyActiveBranch(true)
                            ->setMinDepth(0)
                            ->setMaxDepth(0)
                            ->render();
                        ?>
                    </span>
                </div>
                <div id="mobile-nav-right">
                    <ul class="authentification nav navbar-nav">
                        <li class="dropdown">

                            <a data-toggle="dropdown" class="dropdown-toggle" href="#" aria-expanded="false">
                                <span class="fa fa-user"></span>
                            </a>

                            <?php
                            echo $this->navigation('top_auth_navigation')
                                ->menu()
                                ->setUlClass('dropdown-menu dropdown-menu-right')
                                ->setPartial('layout/navigation/horizontal')
                                ->render();
                            ?>
                        </li>
                    </ul>
                    <ul class="notifications nav navbar-nav">
                        <?php echo $this->notifications()->render(); ?>
                    </ul>
                </div>
            </nav>

            <div id="mobile-nav"></div>

            <?php if (empty($this->placeholder('hideSubjectNav')->getValue())): ?>
                <nav id="subject-nav">
                    <div id="subject-nav-wrapper">
                        <div class="subject-nav-center">
                            <div class="pull-right controls">
                                <?php echo $this->placeholder('controls'); ?>
                            </div>
                            <ol id="breadcrumbs">
                            </ol>
                        </div>
                        <?php echo $this->partial('layout/partials/search'); ?>
                    </div>
                </nav>
            <?php endif; ?>
        </div>
    </header>

    <div id="page">
        <section class="clearfix">
            <div id="content-layout" class="clearfix">
                <div class="flasher">
                </div>

                <div class="home-serlo-row home-row">
                    <div class="home-column">
                        <div class="logo-wrapper">
                            <?php echo $this->brand()->getLogo(); ?>
                            <?php echo $this->brand()->getBrand(); ?>
                        </div>

                        <p>
                            It is our vision to provide high quality education worldwide -
                            completely free of charge and without ads. Like on Wikipedia,
                            every user can create new content or improve upon existing materials.
                            We already provide thousands of articles and solved exercises in German -
                            now it’s time to go international.
                        </p>

                        <a style="margin: 8px;" href="/23727">Learn more <i class="fa fa-arrow-circle-right"></i></a>
                        <a style="margin: 8px;" href="/27469">Participate <i class="fa fa-arrow-circle-right"></i></a>

                    </div>
                </div>

                <div class="home-blue-row home-row">
                    <div></div>
                </div>

                <div class="home-launch-img-row home-row"></div>

                <div class="home-community-wrapper">
                    <div class="home-community-row home-row">

                        <div class="home-column home-col-md-3">
                            <img src="/assets/images/home_participate.svg">
                            <h2>Serlo is a Wiki</h2>
                            <p>
                                You can help us to make education available for free: Become a part of Serlo's
                                online-community.
                            </p>
                            <img src="/assets/images/home_commons.svg"><br>
                            <a href="/27469" class="home-hide-md">Participate <i class="fa fa-arrow-circle-right"></i></a>
                        </div>

                        <div class="home-column home-col-md-3">
                            <img src="/assets/images/home_donate.svg">
                            <h2>Serlo is a nonprofit organization</h2>
                            <p class="text-center">
                                Software development, volunteer support and building the organization requires money -
                                if you’d like to support our mission, please donate.
                            </p>
                            <a href="/39837" class="home-hide-md">Donate <i class="fa fa-arrow-circle-right"></i></a>
                        </div>
                    </div>

                    <div class="home-community-link-row home-row">

                        <div class="home-column home-col-md-3">
                            <a href="/27469" class="home-show-md">Participate <i class="fa fa-arrow-circle-right"></i></a>
                        </div>

                        <div class="home-column home-col-md-3">
                            <a href="/39837" class="home-show-md">Donate <i class="fa fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <div id="footer-push"></div>
</div>

<?php echo $this->partial('layout/partials/footer'); ?>
<?php echo $this->partial('layout/partials/default-modal'); ?>
<?php echo $this->placeholder('modals'); ?>
<?php echo $this->tracking(); ?>
<?php echo $this->partial('layout/partials/noscript'); ?>
</body>
</html>
