<?php echo $this->pageHeader('Uuid recycle bin')->render(); ?>
<table class="table">
    <thead>
        <tr>
            <th><?php echo $this->translate('ID'); ?></th>
            <th><?php echo $this->translate('Title'); ?></th>
            <th><?php echo $this->translate('Type'); ?></th>
            <th><?php echo $this->translate('Actions'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php /* @var $entity \Uuid\Entity\UuidHolder */ ?>
        <?php foreach($this->entities as $entity): ?>
            <tr>
                <td><?php echo $this->normalize()->toTitle($entity); ?></td>
                <td><?php echo $this->normalize()->toAnchor($entity); ?></td>
                <td><?php echo $this->translate($this->normalize()->toType($entity)); ?></td>
                <td>
                    <div class="btn-group">
                        <?php if ($this->isGranted($this->uuid()->getPermission($entity, 'restore'), $entity)): ?>
                            <a class="btn btn-success btn-xs" href="<?php echo $this->url('uuid/restore', array('id' => $entity->getId())); ?>">
                                <span class="fa fa-star"></span>
                            </a>
                        <?php endif; ?>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
