<?php
/**
 * This file is part of Athene2.
 *
 * Copyright (c) 2013-2018 Serlo Education e.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 * you may not use this file except in compliance with the License
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @copyright Copyright (c) 2013-2018 Serlo Education e.V.
 * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache License 2.0
 * @link      https://github.com/serlo-org/athene2 for the canonical source repository
 */
?>
<?php /* @var $router \Contexter\Router\RouterInterface */ ?>
<?php $router = $this->router; ?>
<?php if ($router->hasAdapter()): ?>
    <div class="btn-group<?php echo $this->float ? ' pull-' . $this->float : ''; ?>">
        <button class="dropdown-toggle btn <?php echo $this->class; ?>" type="button" data-toggle="dropdown">
            <strong>?</strong>
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu pull-right" role="menu">
            <?php if (!count($this->matches)): ?>
                <li class="disabled">
                    <a href="#"><?php echo $this->translate('There is no help available for this page yet.'); ?></a>
                </li>
            <?php endif; ?>
            <?php foreach ($this->matches as $context): ?>
                <li>
                    <a target="_blank" href="<?php echo $this->normalize()->toUrl($context->getObject()); ?>">
                        <?php echo $context->getTitle(); ?>
                        <small><?php echo $this->translate(ucfirst($context->getType()->getName())); ?></small>
                    </a>
                </li>
            <?php endforeach; ?>
            <?php if ($this->isGranted('contexter.context.add')): ?>
                <?php $url = $this->url ? $this->url : $this->url(
                    $router->getRouteMatch()->getMatchedRouteName(),
                    $router->getRouteMatch()->getParams(),
                    [],
                    false,
                    false
                ); ?>
                <li>
                    <a href="<?php echo $this->url(
                        'contexter/add',
                        array(),
                        array('query' => array('uri' => $url))
                    ); ?>">
                        <span class="fa fa-plus-sign"></span>&nbsp;
                        <?php echo $this->translate('Add'); ?>
                    </a>
                </li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>