<?php
/**
 * This file is part of Athene2.
 *
 * Copyright (c) 2013-2018 Serlo Education e.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 * you may not use this file except in compliance with the License
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @copyright Copyright (c) 2013-2018 Serlo Education e.V.
 * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache License 2.0
 * @link      https://github.com/serlo-org/athene2 for the canonical source repository
 */
?>
<?php /* @var $router \Contexter\Router\RouterInterface */ ?>
<?php $router = $this->router; ?>
<?php if ($router->hasAdapter()): ?>
    <?php if ($this->type !== NULL): ?>
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <?php echo $this->translate($this->type); ?>
                <span class="caret"></span>
            </a>
    <?php endif; ?>
        <ul class="dropdown-menu pull-right" role="menu">
            <?php /* @var $match \Contexter\Model\ContextModelInterface */ ?>
            <?php foreach ($this->matches as $context): ?>
                <li><a target="_blank" href="<?php echo $this->normalize()->toUrl($context->getObject()); ?>">
                        <?php echo $context->getTitle(); ?>
                    </a>
                </li>
            <?php endforeach; ?>
            <?php if ($this->isGranted('contexter.context.add')): ?>
                <?php $url = $this->url ?: $this->url($router->getRouteMatch()->getMatchedRouteName(), $router->getRouteMatch()->getParams(), [], false, false); ?>
                <li>
                    <a href="<?php echo $this->url('contexter/add', array(), array('query' => array('uri' => $url))); ?>">
                        <span class="fa fa-plus-sign"></span>&nbsp;
                        <?php echo $this->translate('Add'); ?>
                    </a>
                </li>
            <?php endif; ?>
        </ul>
    <?php if ($this->type !== NULL): ?>
        </li>
    <?php endif; ?>
<?php endif; ?>