<footer id="footer">
    <nav class="navbar-default" role="navigation">
        <div class="container-fluid">
            <div class="logo-wrapper">
                <?php echo $this->brand()->getLogo(); ?>
                <?php echo $this->brand()->getBrand(); ?>
            </div>
            <nav>
                <div class="footer-left">
                    <?php
                    echo $this->navigation('footer_left_navigation')
                        ->menu()
                        ->setPartial('layout/navigation/vertical')
                        ->render();
                    ?>
                    <?php
                    echo $this->navigation('social_navigation')
                        ->menu()
                        ->setPartial('layout/navigation/vertical')
                        ->render();
                    ?>
                </div>
                <div class="footer-right">
                    <?php
                    echo $this->navigation('footer_right_navigation')
                        ->menu()
                        ->setPartial('layout/navigation/vertical')
                        ->render();
                    ?>
                </div>
            </nav>
        </div>
    </nav>
</footer>
<?php echo $this->headScript(); ?>
<script type="text/javascript"
        src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
<?php echo $this->inlineScript(); ?>
