<footer id="footer">
    <div class="navbar navbar-default navbar-static-bottom" role="navigation">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#footer-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="footer-collapse">
                <nav class="navbar-inner">
                    <?php
                    echo $this->navigation('footer_navigation')
                        ->menu()
                        ->setUlClass('nav navbar-nav')
                        ->setPartial('layout/navigation/horizontal')
                        ->render();
                    ?>
                </nav>
            </div>
        </div>
    </div>
</footer>
<script type="text/javascript"
        src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
<?php echo $this->inlineScript(); ?>