<footer id="footer">
    <nav class="navbar-default" role="navigation">
        <div class="container-fluid">
            <div class="logo-wrapper">
                <?php echo $this->brand()->getLogo(); ?>
                <?php echo $this->brand()->getBrand(); ?>
            </div>
            <nav>
                <div class="footer-left">
                    <?php
                    echo $this->navigation('footer_left_navigation')
                        ->menu()
                        ->setPartial('layout/navigation/vertical')
                        ->render();
                    ?>
                    <?php
                    echo $this->navigation('social_navigation')
                        ->menu()
                        ->setPartial('layout/navigation/vertical')
                        ->render();
                    ?>
                </div>
                <div class="footer-right">
                    <?php
                    echo $this->navigation('footer_right_navigation')
                        ->menu()
                        ->setPartial('layout/navigation/vertical')
                        ->render();
                    ?>
                </div>
            </nav>
        </div>
    </nav>
</footer>
<script type="text/javascript" src="https://ory-am.github.io/star-ui/dist/scripts/vendor.js"></script>
<script type="text/javascript" src="https://ory-am.github.io/star-ui/dist/scripts/app.js"></script>
<?php echo $this->headScript(); ?>
<?php echo $this->partial('layout/partials/mathjax'); ?>
<?php echo $this->inlineScript(); ?>
<?php echo $this->twigPartial('layout/partials/chat'); ?>
