<?php
/**
 *
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author  Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license LGPL-3.0
 * @license http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link        https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
?>
<header id="header">
    <?php echo $this->partial('layout/partials/top-bar'); ?>

    <nav id="header-nav">
        <a id="mobile-menu-toggle"><i class="fa fa-fw fa-bars"></i></a>
        <a id="brand-link" href="<?php echo $this->url('home'); ?>">
            <?php echo $this->brand()->getLogo(); ?>
            <?php echo $this->brand()->getBrand(); ?>
        </a>
        <span class="subject-title"><?php echo $this->navigation('default_navigation')
            ->menu()
            ->setPartial('layout/navigation/partial/active-subject')
            ->setOnlyActiveBranch(true)
            ->setMinDepth(0)
            ->setMaxDepth(0)
            ->render();
        ?></span>
        <?php /*<div class="slogan"><?php echo $this->translate($this->brand()->getSlogan()); ?></div> */ ?>
    </nav>

    <nav id="subject-nav">
        <a class="subject-anchor"><?php echo $this->navigation('default_navigation')
                ->menu()
                ->setPartial('layout/navigation/partial/active-subject')
                ->setOnlyActiveBranch(true)
                ->setMinDepth(0)
                ->setMaxDepth(0)
                ->render();
            ?></a>

        <div class="subject-nav-center">
            <?php echo $this->placeholder('controls'); ?>
            <ol class="breadcrumbs">
                <li><a href="">Mother</a></li
                ><li><a href="">Fucking</a></li
                ><li><span>Breadcrumbs</span></li>
            </ol>
        </div>

        <?php echo $this->partial('layout/partials/search'); ?>
    </nav>
</header>
