<?php
/**
 * 
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author  Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license LGPL-3.0
 * @license http://opensource.org/licenses/LGPL-3.0 The GNU Lesser General Public License, version 3.0
 * @link        https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
?>
<header id="header">
    <?php echo $this->partial('layout/partials/top-bar'); ?>

    <nav id="subject-nav">
        <a id="brand-link" href="<?php echo $this->url('home'); ?>">
            <?php echo $this->brand()->getLogo(); ?>
            <?php echo $this->brand()->getBrand(); ?>
        </a>
        <div class="subject-dropdown is-inline-block">
            <span class="subject-dropdown-toggle" href="#">
                <span class="subject-dropdown-title">
                    <?php echo $this->navigation('default_navigation')
                                    ->menu()
                                    ->setPartial('layout/navigation/partial/active-subject')
                                    ->setOnlyActiveBranch(true)
                                    ->setMinDepth(0)
                                    ->setMaxDepth(0)
                                    ->render();
                    ?>
                </span>
            </span>
        </div>
        <div class="slogan"><?php echo $this->translate($this->brand()->getSlogan()); ?></div>
    </nav>
</header>