<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->brand()->getHeadTitle(true))->setSeparator(' - '); ?>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headStyle(); ?>
    <?php echo $this->headLink(['rel' => 'icon', 'href' => '/favicon.ico', 'type' => 'image/x-icon']); ?>
    <?php echo $this->headScript(); ?>
    <?php /* excluded for now <meta name="viewport" content="width=device-width, user-scalable=no">*/ ?>
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400italic,400,700,600' rel='stylesheet'
          type='text/css'>
</head>