<aside class="side-navigation side-element">
    <div class="layout-toggle">
        <i class="fa fa-bars"></i>
        <i class="fa fa-times"></i>
    </div>
    <div class="side-element-inner">
        <?php
        echo $this->navigation('default_navigation')
                    ->menu()
                    ->setPartial('layout/navigation/side-navigation')
                    ->setOnlyActiveBranch(false)
                    ->setMinDepth(0)
                    ->setMaxDepth(1)
                    ->setUlClass('nav clear')
                    ->render();
        ?>
        <ul id="side-navigation-social">
            <li>
                <a href="http://serlo.us7.list-manage2.com/subscribe?u=23f4b04bf70ea485a766e532d&id=a7bb2bbc4f">Newsletter</a>
            </li>
            <li>
                <a href="https://www.facebook.com/serlo.org">
                    <span class="fa fa-facebook-square"></span>
                </a>
            </li>
            <li>
                <a href="https://twitter.com/de_Serlo">
                    <span class="fa fa-twitter-square"></span>
                </a>
            </li>
        </ul>
    </div>
</aside>
