<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
        displayAlign: 'left',
        extensions: ['tex2jax.js', 'fast-preview.js'],
        jax: ['input/TeX', 'output/SVG', 'output/CommonHTML'],
        skipStartupTypeset: true,
        tex2jax: {
            inlineMath: [
                ['%%', '%%']
            ],
            displayMath: [
                ["$$", "$$"]
            ],
        },
        'HTML-CSS': {
            scale: 100,
            linebreaks: {
                automatic: true
            },
            preferredFont: 'STIX'
        },
        SVG: {
            linebreaks: {
                automatic: true
            },
            font: 'STIX-Web'
        },
        showProcessingMessages: false,
        TeX: {
            extensions: ['mhchem.js']
        }
    });
</script>
<script type="text/javascript" async
        src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML&locale=<?php echo $this->currentLanguage(); ?>">
</script>