<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
        displayAlign: 'left',
        extensions: ['tex2jax.js', 'CHTML-preview.js'],
        jax: ['input/TeX', 'output/SVG', 'output/CommonHTML'],
        skipStartupTypeset: true,
        tex2jax: {
            inlineMath: [
                ['%%', '%%']
            ],
            displayMath: [
                ["$$", "$$"]
            ],
        },
        'HTML-CSS': {
            scale: 100,
            linebreaks: {
                automatic: true
            }
        },
        SVG: {
            linebreaks: {
                automatic: true
            }
        },
        showProcessingMessages: false
    });
</script>
<script type="text/javascript"
        src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
