<?php
/**
 * This file is part of Athene2.
 *
 * Copyright (c) 2013-2019 Serlo Education e.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 * you may not use this file except in compliance with the License
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @copyright Copyright (c) 2013-2019 Serlo Education e.V.
 * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache License 2.0
 * @link      https://github.com/serlo-org/athene2 for the canonical source repository
 */
?>
<noscript id="noscript-modal">
    <input type="checkbox" class="modal-closing-trick" id="modal-closing-trick">

    <div class="modal fade in is-block" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="false">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title"><?php echo $this->translate(
                            'This site makes heavy use of JavaScript!'
                        ); ?></h4>
                </div>
                <div class="modal-body">
                    <p><?php echo $this->translate('Please enable JavaScript to use this site.'); ?></p>
                </div>
                <div class="modal-footer">
                    <a href="http://www.enable-javascript.com/" class="btn btn-primary"><?php echo $this->translate(
                            'Show me how to enable JavaScript'
                        ); ?></a>

                    <label class="btn btn-primary btn-transparent" for="modal-closing-trick">
                        <?php echo $this->translate(
                            'Close'
                        ); ?>
                    </label>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->
    <div class="modal-backdrop fade in"></div>
</noscript>