<noscript>
    <div class="modal fade in is-block" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="false">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title"><?php echo $this->translate(
                            'This site makes heavy use of JavaScript!'
                        ); ?></h4>
                </div>
                <div class="modal-body">
                    <p><?php echo $this->translate('Please enable JavaScript to use this site.'); ?></p>
                </div>
                <div class="modal-footer">
                    <a href="http://www.enable-javascript.com/" class="btn btn-primary"><?php echo $this->translate(
                            'Show me how to enable JavaScript'
                        ); ?></a>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->
    <div class="modal-backdrop fade in"></div>
</noscript>