<?php
/**
 * This file is part of Athene2.
 *
 * Copyright (c) 2013-2018 Serlo Education e.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 * you may not use this file except in compliance with the License
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @copyright Copyright (c) 2013-2018 Serlo Education e.V.
 * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache License 2.0
 * @link      https://github.com/serlo-org/athene2 for the canonical source repository
 */
?>
<div class="flasher">
    <?php
if ($this->flashMessenger()->hasSuccessMessages()) {
    echo '<div class="alert alert-success">';
    echo '<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>';
    foreach ($this->flashmessenger()->getSuccessMessages() as $message) {
        echo '<p>' . $this->translate($message) . '</p>';
    }

    echo '</div>';
}

if ($this->flashMessenger()->hasErrorMessages()) {
    echo '<div class="alert alert-danger">';
    echo '<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>';
    foreach ($this->flashmessenger()->getErrorMessages() as $message) {
        echo '<p>' . $this->translate($message) . '</p>';
    }

    echo '</div>';
}

if ($this->flashMessenger()->hasMessages()) {
    echo '<div class="alert alert-info">';
    echo '<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>';
    foreach ($this->flashmessenger()->getMessages() as $message) {
        echo '<p>' . $this->translate($message) . '</p>';
    }

    echo '</div>';
}
?>
</div>
