<?php if (!empty($this->registry()->get('rnav'))): ?>
<?php $isCourse = $this->registry()->get('rnav-is-course');?>
<aside class="side-element side-context <?php if (!empty($isCourse) && $isCourse) : echo 'side-context-course'; endif; ?> ">
    <div id="sidebar-toggle" class="layout-toggle">
        <i class="fa fa-bars"></i>
        <i class="fa fa-times"></i>
    </div>
    <div class="side-element-inner">
        <?php if (!$isCourse): ?>
            <i class="fa fa-asterisk"></i>
        <?php endif; ?>
        <?php echo $this->registry()->get('rnav'); ?>
    </div>
</aside>
<?php endif;?>