<?php if (!$this->layout()->hideRightSidebar): ?>
    <?php if (!empty($this->registry()->get('rnav'))): ?>
    <aside class="side-element side-context">
        <div id="sidebar-toggle" class="layout-toggle">
            <i class="fa fa-bars"></i>
            <i class="fa fa-times"></i>
        </div>
        <div class="side-element-inner">
            <i class="fa fa-asterisk"></i>
            <?php echo $this->registry()->get('rnav'); ?>
        </div>
    </aside>
    <?php endif;?>
    <aside class="side-element side-context">
        <div id="ory-editor-meta-data-wrapper" style="display:none;">
            <div id="ory-editor-meta-data"></div>
        </div>
    </aside>
<?php endif;?>
