<?php echo $this->partial('layout/partials/mathjax'); ?>
<?php echo $this->headScript(); ?>
<?php echo $this->inlineScript(); ?>
<script src="<?php echo $this->assetsHost(); ?>commons.js" type="text/javascript"></script>
<script src="<?php echo $this->assetsHost(); ?>main.js" type="text/javascript"></script>
<script src="<?php echo $this->assetsHost(); ?>oryEditor.js" type="text/javascript"></script>
<?php echo $this->partial('layout/partials/popup'); ?>
