<?php echo $this->partial('layout/partials/mathjax'); ?>
<?php echo $this->headScript(); ?>
<?php echo $this->inlineScript(); ?>
<?php if ($this->prerelease()): ?>
  <script src="http://localhost:8081/commons.js" type="text/javascript"></script>
  <script src="http://localhost:8081/main.js" type="text/javascript"></script>
<?php else: ?>
  <script src="/assets/libs.js" type="text/javascript"></script>
  <script src="/assets/scripts.js" type="text/javascript"></script>
<?php endif; ?>
<?php /* echo $this->partial('layout/partials/popup'); */ ?>
