<div id="search-content">

<form method="get" class="form-search inline" role="search" action="http://localhost:4567/search">
    <div class="form-group">
        <div class="input-group">
            <input id="search-input" type="search" placeholder="<?php echo $this->translate('Search'); ?>" tabindex="1" name="q" />
            <div class="input-group-addon">
                <button type="submit" class="btn"><i class="fa fa-lg fa-search"></i>
                </button>
            </div>
        </div>
    </div>
</form>

</div>

