<?php
/**
 * This file is part of Athene2.
 *
 * Copyright (c) 2013-2018 Serlo Education e.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 * you may not use this file except in compliance with the License
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @copyright Copyright (c) 2013-2018 Serlo Education e.V.
 * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache License 2.0
 * @link      https://github.com/serlo-org/athene2 for the canonical source repository
 */
?>
<div id="search-content">

<form method="get" class="form-search inline" role="search" action="<?php echo $this->url('search'); ?>">
    <div class="form-group">
        <div class="input-group">
            <input id="search-input" type="search" placeholder="<?php echo $this->translate('Search'); ?>" tabindex="1" name="q" />
            <div class="input-group-addon">
                <button type="submit" class="btn"><i class="fa fa-lg fa-search"></i>
                </button>
            </div>
        </div>
    </div>
</form>

</div>
