<div id="search-content">
    <input id="search-input" class="input-search" type="search" placeholder="<?php echo $this->translate('Search'); ?>" tabindex="1"/><i class="glyphicon glyphicon-search"></i>
    <ul id="search-results" class="nav"></ul>
    <div id="search-help">
        <div class="row">
            <div class="col-xs-12">
                <p>
                    <?php echo $this->translate('Start typing, hit enter and receive matching results.'); ?>
                </p>
            </div>
        </div>
    </div>
</div>