<nav id="serlo-menu" class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="top-bar-collapse">
            <nav class="navbar-inner">
                <?php
                // top left navigation
                echo $this->navigation('top_left_navigation')
                    ->menu()
                    ->setUlClass('nav navbar-nav')
                    ->setPartial('layout/navigation/horizontal')
                    ->render();
                // top right navigation
                ?>
                <?php
                echo $this->navigation('top_auth_navigation')
                    ->menu()
                    ->setUlClass('nav navbar-nav navbar-right authentication')
                    ->setPartial('layout/navigation/horizontal')
                    ->render();
                ?>
                <ul class="nav navbar-nav pull-right notifications hidden-xs">
                    <?php echo $this->notifications()->render(); ?>
                </ul>
                <?php
                echo $this->navigation('top_right_navigation')
                    ->menu()
                    ->setUlClass('nav navbar-nav navbar-right')
                    ->setPartial('layout/navigation/horizontal')
                    ->render();
                ?>
                <?php //echo $this->instance()->renderSelect(); ?>
            </nav>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>
